
# export the keys from the aws as environmnet varialbe.
#export AWS_ACCESS_KEY=xxxxxxxx
#export AWS_SECRET_KEY=xxxxxxxx

--- # EC2- start/stop/terminate Module Use Example
- hosts: localhost
  connection: local
  remote_user: test
  tasks:
  -  name: manage the state of an instance
     ec2:
       region: eu-west-1
       image: ami-aa1xxxxdd9
       group: EC2-Security
       instance_type: t2.micro
       count: 1
       wait: yes
       vpc_subnet_id: subnet-xxxxxxxx705f
       assign_public_ip: yes
     register: NewInstance
~                       



********************************************************************
output of the program

*********************************************************************

